ALTER TABLE travel_requests
MODIFY COLUMN status ENUM(
    'DRAFT',
    'SUBMITTED',
    'MANAGER_APPROVED',
    'FINANCE_APPROVED',
    'MANAGER_REJECTED',
    'FINANCE_REJECTED',
    'COMPLETED',
    'CANCELLED'
) NOT NULL;