export enum RequestStatus {
    DRAFT = 'DRAFT',
    SUBMITTED = 'SUBMITTED',
    MANAGER_APPROVED = 'MANAGER_APPROVED',
    FINANCE_APPROVED = 'FINANCE_APPROVED',
    MANAGER_REJECTED = 'MANAGER_REJECTED',
    FINANCE_REJECTED = 'FINANCE_REJECTED',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED'
}