export enum RequestStatus {
    DRAFT = 'DRAFT',
    SUBMITTED = 'SUBMITTED',
    MANAGER_APPROVED = 'MANAGER_APPROVED',
    FINANCE_APPROVED = 'FINANCE_APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED'
}